### ISSUE TITLE
Please add a screen shot of the theme

### ISSUE THREAD

**Issue by unixorn** [zakkak/mygnzh#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by zakkak** [comment]
I no longer use this theme. I tried loading it but it seems to be broken, so I can't provide any screenshots, sorry.

**Comment by unixorn** [comment]
Ok, thanks
